volumes:
  waygrid_kafka_data_1: { }
  waygrid_kafka_data_2: { }
  waygrid_kafka_data_3: { }
  waygrid_redis_data_1: { }
  waygrid_redis_data_2: { }
  waygrid_redis_data_3: { }
  waygrid_redis_data_4: { }
  waygrid_redis_data_5: { }
  waygrid_redis_data_6: { }
  waygrid_redisinsight_data: { }

x-redis-cluster-base: &redis-cluster-base
  image: bitnami/redis-cluster

x-kafka-cluster-base: &kafka-cluster-base
  image: bitnami/kafka

services:
  waygrid-service:
    build:
      context: .
    å

  waygrid-kafka-node-1:
    <<: *kafka-cluster-base
    hostname: waygrid-kafka-node-1
    container_name: waygrid-kafka-node-1
    volumes:
      - waygrid_kafka_data_1:/var/lib/kafka/data
    user: root
    ports:
      #      - '9092:9092'
      - '29092:29092'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://waygrid-kafka-node-1:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_BROKER_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWA
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@waygrid-kafka-node-1:9093,2@waygrid-kafka-node-2:9095,3@waygrid-kafka-node-3:9097
      - ALLOW_PLAINTEXT_LISTENER=yes

  waygrid-kafka-node-2:
    <<: *kafka-cluster-base
    hostname: waygrid-kafka-node-2
    container_name: waygrid-kafka-node-2
    volumes:
      - waygrid_kafka_data_2:/var/lib/kafka/data
    user: root
    ports:
      #      - '9094:9094'
      - '29094:29094'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9094,CONTROLLER://:9095,PLAINTEXT_HOST://:29094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://waygrid-kafka-node-2:9094,PLAINTEXT_HOST://localhost:29094
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_BROKER_ID=2
      - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWA
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@waygrid-kafka-node-1:9093,2@waygrid-kafka-node-2:9095,3@waygrid-kafka-node-3:9097
      - ALLOW_PLAINTEXT_LISTENER=yes

  waygrid-kafka-node-3:
    <<: *kafka-cluster-base
    hostname: waygrid-kafka-node-3
    container_name: waygrid-kafka-node-3
    volumes:
      - waygrid_kafka_data_3:/var/lib/kafka/data
    user: root
    ports:
      #      - '9096:9096'
      - '29096:29096'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9096,CONTROLLER://:9097,PLAINTEXT_HOST://:29096
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://waygrid-kafka-node-3:9096,PLAINTEXT_HOST://localhost:29096
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_BROKER_ID=3
      - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWA
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@waygrid-kafka-node-1:9093,2@waygrid-kafka-node-2:9095,3@waygrid-kafka-node-3:9097
      - ALLOW_PLAINTEXT_LISTENER=yes

  waygrid-redpanda:
    image: docker.redpanda.com/redpandadata/console:latest
    hostname: waygrid-redpanda
    container_name: waygrid-redpanda
    ports:
      - "1336:8080"
    environment:
      - KAFKA_BROKERS=waygrid-kafka-node-1:9092,waygrid-kafka-node-2:9094,waygrid-kafka-node-3:9096

  waygrid-redis-node-1:
    <<: *redis-cluster-base
    hostname: waygrid-redis-node-1
    container_name: waygrid-redis-node-1
    volumes:
      - waygrid_redis_data_1:/bitnami/redis/data
    depends_on:
      - waygrid-redis-node-2
      - waygrid-redis-node-3
      - waygrid-redis-node-4
      - waygrid-redis-node-5
      - waygrid-redis-node-6
      - waygrid-redis-insight
    ports:
      - '6379:6379'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_CLUSTER_CREATOR=yes'
      - 'REDIS_NODES=waygrid-redis-node-1 waygrid-redis-node-2 waygrid-redis-node-3 waygrid-redis-node-4 waygrid-redis-node-5 waygrid-redis-node-6'

  waygrid-redis-node-2:
    <<: *redis-cluster-base
    hostname: waygrid-redis-node-2
    container_name: waygrid-redis-node-2
    volumes:
      - waygrid_redis_data_2:/bitnami/redis/data
    ports:
      - '6380:6379'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=waygrid-redis-node-1 waygrid-redis-node-2 waygrid-redis-node-3 waygrid-redis-node-4 waygrid-redis-node-5 waygrid-redis-node-6'

  waygrid-redis-node-3:
    <<: *redis-cluster-base
    hostname: waygrid-redis-node-3
    container_name: waygrid-redis-node-3
    volumes:
      - waygrid_redis_data_3:/bitnami/redis/data
    ports:
      - '6381:6379'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=waygrid-redis-node-1 waygrid-redis-node-2 waygrid-redis-node-3 waygrid-redis-node-4 waygrid-redis-node-5 waygrid-redis-node-6'

  waygrid-redis-node-4:
    <<: *redis-cluster-base
    hostname: waygrid-redis-node-4
    container_name: waygrid-redis-node-4
    volumes:
      - waygrid_redis_data_4:/bitnami/redis/data
    ports:
      - '6382:6379'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=waygrid-redis-node-1 waygrid-redis-node-2 waygrid-redis-node-3 waygrid-redis-node-4 waygrid-redis-node-5 waygrid-redis-node-6'

  waygrid-redis-node-5:
    <<: *redis-cluster-base
    hostname: waygrid-redis-node-5
    container_name: waygrid-redis-node-5
    volumes:
      - waygrid_redis_data_5:/bitnami/redis/data
    ports:
      - '6383:6379'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=waygrid-redis-node-1 waygrid-redis-node-2 waygrid-redis-node-3 waygrid-redis-node-4 waygrid-redis-node-5 waygrid-redis-node-6'

  waygrid-redis-node-6:
    <<: *redis-cluster-base
    hostname: waygrid-redis-node-6
    container_name: waygrid-redis-node-6
    volumes:
      - waygrid_redis_data_6:/bitnami/redis/data
    ports:
      - '6384:6379'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=waygrid-redis-node-1 waygrid-redis-node-2 waygrid-redis-node-3 waygrid-redis-node-4 waygrid-redis-node-5 waygrid-redis-node-6'

  waygrid-redis-insight:
    image: redis/redisinsight
    hostname: waygrid-redis-node-insight
    container_name: waygrid-redis-node-insight
    volumes:
      - waygrid_redisinsight_data:/data
    ports:
      - "5540:5540"

  waygrid-postgres-leg-scheduler:
    image: postgres:latest
    hostname: waygrid-postgres-leg-scheduler
    container_name: waygrid-postgres-leg-scheduler
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=waygrid
      - POSTGRES_PASSWORD=Password1
      - POSTGRES_DB=waygrid-leg-scheduler

  waygrid-otel-collector:
    image: otel/opentelemetry-collector-contrib
    hostname: waygrid-otel-collector
    container_name: waygrid-otel-collector
    volumes:
      - ./.docker/opentelemetry/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
    command: [ --config=/etc/otel-collector-config.yaml ]

  waygrid-jaeger:
    image: jaegertracing/all-in-one:latest
    hostname: waygrid-jaeger
    container_name: waygrid-jaeger
    volumes:
      - ./.docker/jaeger/jaeger-ui.json:/etc/jaeger/jaeger-ui.json
    ports:
      - "16685:16685" # GRPC
      - "16686:16686" # UI
    environment:
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://waygrid-prometheus:9090
    command: --query.ui-config /etc/jaeger/jaeger-ui.json

  waygrid-prometheus:
    image: prom/prometheus:latest
    hostname: waygrid-prometheus
    container_name: waygrid-prometheus
    volumes:
      - ./.docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  waygrid-grafana:
    image: grafana/grafana-oss
    hostname: waygrid-grafana
    container_name: waygrid-grafana
    volumes:
      - ./.docker/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    ports:
      - "3000:3000"