volumes:
  waygrid_kafka_data_1: { }
  waygrid_kafka_data_2: { }
  waygrid_kafka_data_3: { }

x-kafka-cluster-base: &kafka-cluster-base
  image: bitnami/kafka

services:
  waygrid-kafka-node-1:
    <<: *kafka-cluster-base
    hostname: waygrid-kafka-node-1
    container_name: waygrid-kafka-node-1
    volumes:
      - waygrid_kafka_data_1:/var/lib/kafka/data
    user: root
    ports:
      #      - '9092:9092'
      - '29092:29092'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://waygrid-kafka-node-1:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_BROKER_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWA
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@waygrid-kafka-node-1:9093,2@waygrid-kafka-node-2:9095,3@waygrid-kafka-node-3:9097
      - ALLOW_PLAINTEXT_LISTENER=yes

  waygrid-kafka-node-2:
    <<: *kafka-cluster-base
    hostname: waygrid-kafka-node-2
    container_name: waygrid-kafka-node-2
    volumes:
      - waygrid_kafka_data_2:/var/lib/kafka/data
    user: root
    ports:
      #      - '9094:9094'
      - '29094:29094'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9094,CONTROLLER://:9095,PLAINTEXT_HOST://:29094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://waygrid-kafka-node-2:9094,PLAINTEXT_HOST://localhost:29094
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_BROKER_ID=2
      - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWA
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@waygrid-kafka-node-1:9093,2@waygrid-kafka-node-2:9095,3@waygrid-kafka-node-3:9097
      - ALLOW_PLAINTEXT_LISTENER=yes

  waygrid-kafka-node-3:
    <<: *kafka-cluster-base
    hostname: waygrid-kafka-node-3
    container_name: waygrid-kafka-node-3
    volumes:
      - waygrid_kafka_data_3:/var/lib/kafka/data
    user: root
    ports:
      #      - '9096:9096'
      - '29096:29096'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9096,CONTROLLER://:9097,PLAINTEXT_HOST://:29096
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://waygrid-kafka-node-3:9096,PLAINTEXT_HOST://localhost:29096
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_BROKER_ID=3
      - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWA
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@waygrid-kafka-node-1:9093,2@waygrid-kafka-node-2:9095,3@waygrid-kafka-node-3:9097
      - ALLOW_PLAINTEXT_LISTENER=yes

  waygrid-redpanda:
    image: docker.redpanda.com/redpandadata/console:latest
    hostname: waygrid-redpanda
    container_name: waygrid-redpanda
    ports:
      - "1336:8080"
    environment:
      - KAFKA_BROKERS=waygrid-kafka-node-1:9092,waygrid-kafka-node-2:9094,waygrid-kafka-node-3:9096

  waygrid-otel-lgtm:
      image: grafana/otel-lgtm
      hostname: waygrid-otel-lgtm
      container_name: waygrid-otel-lgtm
      ports:
        - "3000:3000"
        - "4317:4317"
        - "4318:4318"
      environment :
        - OTEL_METRIC_EXPORT_INTERVAL=500
