addSbtPlugin("org.jetbrains.scala" % "sbt-ide-settings" % "1.1.2")
addSbtPlugin("org.typelevel"       % "sbt-tpolecat"             % "0.5.0")
addSbtPlugin("io.spray"            % "sbt-revolver"             % "0.10.0")
addSbtPlugin("com.github.sbt"      % "sbt-native-packager"      % "1.9.16")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"             % "2.5.2")
addSbtPlugin("ch.epfl.scala"       % "sbt-scalafix"             % "0.11.0")
addSbtPlugin("org.portable-scala"  % "sbt-scalajs-crossproject" % "1.3.2")
addSbtPlugin("com.github.reibitto" % "sbt-welcome"              % "0.4.0")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.12.0")
addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.6.4")
addDependencyTreePlugin